services:
  - type: web
    name: ilmeori
    runtime: ruby
    plan: starter
    region: singapore
    buildCommand: "bundle install && SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile"
    startCommand: "bash bin/release && bundle exec rails server -b 0.0.0.0"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        sync: false
