#coding:UTF-8
_erbout = +''; _erbout.<< "<div style=\"min-height:100vh; background:#f5f5f5; padding-bottom:env(safe-area-inset-bottom);\">\n  ".freeze
; _erbout.<< "\n  <div style=\"background:white; padding:18px 20px 14px 20px; border-bottom:1px solid #ececec; position:sticky; top:0; z-index:30;\" class=\"safe-sticky-header\">\n    <div style=\"display:flex; justify-content:space-between; align-items:center;\">\n      <div style=\"font-size:24px; color:#111827; font-weight:900; cursor:pointer;\" onclick=\"openDrawer()\">\xE2\x98\xB0</div>\n      <div style=\"font-size:20px; font-weight:900; color:#111827;\">\xEB\xB9\x84\xEC\xA6\x88\xEB\x8B\x88\xEC\x8A\xA4 \xEC\x84\x9C\xEB\xA5\x98 \xEC\xA7\x80\xEA\xB0\x91</div>\n      <div style=\"width:24px;\"></div>\n    </div>\n  </div>\n\n  <div style=\"padding:16px;\">\n    <div style=\"background:white; border-radius:20px; padding:20px; box-shadow:0 2px 10px rgba(0,0,0,0.02); margin-top:2px;\">\n      <div style=\"display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:16px;\">\n        <div>\n          <div style=\"font-size:16px; font-weight:900; color:#111827; display:flex; align-items:center; gap:6px;\">\n            <span>\xF0\x9F\x92\xBC</span> \xEB\x82\xB4 \xEB\xB9\x84\xEC\xA6\x88\xEB\x8B\x88\xEC\x8A\xA4 \xED\x8C\xA9\n          </div>\n          <div style=\"font-size:12px; color:#6b7280; font-weight:600; margin-top:4px;\">\xEB\xAA\x85\xED\x95\xA8, \xEC\x82\xAC\xEC\x97\x85\xEC\x9E\x90, \xEC\x9D\xBC\xEB\xB0\x98/\xEC\x82\xAC\xEC\x97\x85\xEC\x9E\x90 \xED\x86\xB5\xEC\x9E\xA5 \xEC\x82\xAC\xEB\xB3\xB8\xEC\x9D\x84 \xEB\x93\xB1\xEB\xA1\x9D\xED\x95\x98\xEC\x84\xB8\xEC\x9A\x94.</div>\n        </div>\n        <span style=\"background:#dbeafe; color:#1e40af; font-size:10px; font-weight:900; padding:4px 8px; border-radius:99px;\">FREE \xE2\x9C\xA8</span>\n      </div>\n        ".freeze



















;  if notice.present? ; _erbout.<< "<p style=\"color: green; margin-bottom: 12px; text-align:center; font-size:13px; font-weight:700;\">".freeze; _erbout.<<(( notice ).to_s); _erbout.<< "</p>".freeze;  end ; _erbout.<< "\n        ".freeze
;  if alert.present? ; _erbout.<< "<p style=\"color: red; margin-bottom: 12px; text-align:center; font-size:13px; font-weight:700;\">".freeze; _erbout.<<(( alert ).to_s); _erbout.<< "</p>".freeze;  end ; _erbout.<< "\n\n        <!-- \xEC\x88\xA8\xEA\xB9\x80 \xEC\x82\xAD\xEC\xA0\x9C \xED\x8F\xBC -->\n        <form id=\"delete-doc-form\" action=\"\" method=\"post\" style=\"display:none;\">\n          <input type=\"hidden\" name=\"_method\" value=\"delete\">\n          ".freeze




; _erbout.<<(( hidden_field_tag :authenticity_token, form_authenticity_token ).to_s); _erbout.<< "\n        </form>\n        <script>\n          function submitDeleteDocument(type) {\n            if (confirm(\"\xEC\xA0\x95\xEB\xA7\x90\xEB\xA1\x9C \xEC\x82\xAD\xEC\xA0\x9C\xED\x95\x98\xEC\x8B\x9C\xEA\xB2\xA0\xEC\x8A\xB5\xEB\x8B\x88\xEA\xB9\x8C?\")) {\n              const form = document.getElementById('delete-doc-form');\n              form.action = '/my_account/documents/' + type;\n              form.submit();\n            }\n          }\n        </script>\n\n        ".freeze











; _erbout.<<(( form_with model: current_user, url: update_my_account_documents_path, method: :patch, local: true, html: { multipart: true } do |f| ).to_s); _erbout.<< "\n          \n          <!-- \xED\x86\xB5\xEC\x9E\xA5 \xEB\xAA\x85\xED\x95\xA8 \xEC\x9E\x90\xEB\x8F\x99 \xEC\x83\x9D\xEC\x84\xB1\xEA\xB8\xB0 -->\n          <div style=\"background:#f0f9ff; border:1px solid #bae6fd; border-radius:16px; padding:16px; margin-bottom:20px; box-shadow:0 4px 12px rgba(14,165,233,0.1);\">\n            <div style=\"display:flex; justify-content:space-between; align-items:center; margin-bottom:12px;\">\n              <div style=\"font-size:15px; font-weight:900; color:#0369a1; display:flex; align-items:center; gap:6px;\">\n                \xF0\x9F\x92\xB3 \xEC\x8A\xA4\xEB\xA7\x88\xED\x8A\xB8 \xED\x86\xB5\xEC\x9E\xA5 \xEB\xAA\x85\xED\x95\xA8 \xEC\x83\x9D\xEC\x84\xB1\xEA\xB8\xB0\n              </div>\n            </div>\n            <div style=\"font-size:12px; color:#0284c7; font-weight:600; margin-bottom:16px; line-height:1.5;\">\n              \xEA\xB3\x84\xEC\xA2\x8C\xEB\xB2\x88\xED\x98\xB8\xEB\xA5\xBC \xEC\x9E\x85\xEB\xA0\xA5\xED\x95\x98\xEB\xA9\xB4 \xEC\x8B\xA0\xEB\xA2\xB0\xEA\xB0\x90\xEC\x9D\x84 \xEC\xA3\xBC\xEB\x8A\x94 \xEB\xA9\x8B\xEC\xA7\x84 \xED\x86\xB5\xEC\x9E\xA5 \xEB\xAA\x85\xED\x95\xA8\xEC\x9D\xB4 \xEC\xA6\x89\xEC\x8B\x9C \xEC\x83\x9D\xEC\x84\xB1\xEB\x90\xA9\xEB\x8B\x88\xEB\x8B\xA4. \xEC\xA0\x80\xEC\x9E\xA5 \xEB\xB2\x84\xED\x8A\xBC\xEC\x9D\x84 \xEB\x88\x84\xEB\xA5\xBC \xED\x95\x84\xEC\x9A\x94 \xEC\x97\x86\xEC\x9D\xB4 \xEB\xB0\x94\xEB\xA1\x9C <strong>'\xEA\xB3\xB5\xEC\x9C\xA0\xED\x95\x98\xEA\xB8\xB0'</strong>\xEB\xA7\x8C \xEB\x88\x84\xEB\xA5\xB4\xEB\xA9\xB4 \xEC\xB9\xB4\xED\x86\xA1\xEC\x97\x90 \xEA\xB2\xB0\xEC\xA0\x9C \xEC\xA0\x95\xEB\xB3\xB4\xEA\xB0\x80 \xEC\x99\x84\xEB\xB2\xBD\xED\x95\x98\xEA\xB2\x8C \xEB\xB3\xB5\xEC\x82\xAC\xEB\x90\xA9\xEB\x8B\x88\xEB\x8B\xA4!\n            </div>\n\n            <!-- Inputs -->\n            <div style=\"display:grid; grid-template-columns:1fr; gap:10px; margin-bottom:16px;\">\n              ".freeze














; _erbout.<<(( f.select :bank_name, options_for_select(['신한은행', '국민은행', '우리은행', '하나은행', '농협은행', 'IBK기업은행', 'KDB산업은행', '수협은행', '카카오뱅크', '토스뱅크', '케이뱅크', '새마을금고', '우체국', '신협', '저축은행', '산림조합', '씨티은행', 'SC제일은행', '대구은행', '부산은행', '광주은행', '제주은행', '전북은행', '경남은행', '기타'], current_user.bank_name), {prompt: '은행을 선택하세요'}, {id: 'bankNameInput', style: "width:100%; padding:14px; border-radius:12px; border:1px solid #cbd5e1; font-weight:800; font-size:14px; color:#1e293b;", required: true} ).to_s); _erbout.<< "\n              ".freeze
; _erbout.<<(( f.text_field :bank_account_number, id: 'bankAccountInput', placeholder: "계좌번호 (예: 110-123-456789)", style: "width:100%; padding:14px; border-radius:12px; border:1px solid #cbd5e1; font-weight:800; font-size:14px; color:#1e293b;", value: current_user.bank_account_number ).to_s); _erbout.<< "\n              ".freeze
; _erbout.<<(( f.text_field :bank_account_holder, id: 'bankHolderInput', placeholder: "예금주 성함", style: "width:100%; padding:14px; border-radius:12px; border:1px solid #cbd5e1; font-weight:800; font-size:14px; color:#1e293b;", value: current_user.bank_account_holder ).to_s); _erbout.<< "\n            </div>\n\n            <!-- Preview Card -->\n            <div id=\"bankCardElement\" style=\"position:relative; width:100%; aspect-ratio:1.586; border-radius:16px; background:linear-gradient(135deg, #2563eb, #1e3a8a); color:white; padding:24px; box-shadow:0 10px 25px rgba(0,0,0,0.15); overflow:hidden; margin-bottom:16px; display:flex; flex-direction:column; justify-content:space-between; box-sizing:border-box; transition: all 0.3s ease;\">\n              <!-- Background pattern -->\n              <div style=\"position:absolute; top:-50px; right:-50px; width:150px; height:150px; background:rgba(255,255,255,0.1); border-radius:50%;\"></div>\n              <div style=\"position:absolute; bottom:-30px; left:-30px; width:100px; height:100px; background:rgba(255,255,255,0.05); border-radius:50%;\"></div>\n              <div style=\"position:absolute; top:40%; right:10%; width:60px; height:60px; background:rgba(255,255,255,0.08); border-radius:12px; transform:rotate(15deg);\"></div>\n              \n              <div style=\"position:relative; z-index:1; display:flex; justify-content:space-between; align-items:flex-start;\">\n                <div id=\"cardBankName\" style=\"font-size:20px; font-weight:900; letter-spacing:-0.5px; text-shadow:0 1px 3px rgba(0,0,0,0.1);\">".freeze










; _erbout.<<(( current_user.bank_name.presence || '신한은행' ).to_s); _erbout.<< "</div>\n                <div style=\"font-size:24px; filter:drop-shadow(0 2px 4px rgba(0,0,0,0.1));\">\xF0\x9F\x92\xB3</div>\n              </div>\n\n              <div style=\"position:relative; z-index:1; margin-top:auto;\">\n                <div id=\"cardAccountNumber\" style=\"font-size:22px; font-weight:800; letter-spacing:1px; margin-bottom:12px; font-family:'Courier New', Courier, monospace; text-shadow:0 2px 4px rgba(0,0,0,0.2);\">".freeze




; _erbout.<<(( current_user.bank_account_number.presence || '110-123-456789' ).to_s); _erbout.<< "</div>\n                <div style=\"display:flex; justify-content:space-between; align-items:flex-end;\">\n                  <div style=\"display:flex; flex-direction:column;\">\n                    <span style=\"font-size:10px; opacity:0.8; font-weight:700; margin-bottom:2px; letter-spacing:0.5px;\">\xEC\x84\xB1\xED\x95\xA8</span>\n                    <span id=\"cardHolderName\" style=\"font-size:16px; font-weight:900; letter-spacing:1px; text-shadow:0 1px 3px rgba(0,0,0,0.1);\">".freeze



; _erbout.<<(( current_user.bank_account_holder.presence || '김일잘' ).to_s); _erbout.<< "</span>\n                  </div>\n                  <div style=\"font-size:9px; font-weight:800; opacity:0.8; text-align:right; line-height:1.2; text-shadow:0 1px 2px rgba(0,0,0,0.1);\">\n                    \xEC\x8A\xA4\xEB\xA7\x88\xED\x8A\xB8\xED\x95\x9C \xED\x98\x84\xEC\x9E\xA5 \xEA\xB4\x80\xEB\xA6\xAC<br>\xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC \xEC\x95\xB1\n                  </div>\n                </div>\n              </div>\n            </div>\n\n            <!-- Action Buttons -->\n            <div style=\"display:flex; flex-direction:column; gap:8px;\">\n              <button type=\"button\" onclick=\"generateAndShareBankCard()\" id=\"shareBankCardBtn\" style=\"width:100%; background:#0f172a; color:white; border:none; padding:16px; border-radius:12px; font-size:15px; font-weight:900; cursor:pointer; box-shadow:0 6px 16px rgba(15,23,42,0.3); display:flex; justify-content:center; align-items:center; gap:8px; transition:transform 0.1s;\">\n                <span>\xF0\x9F\x9A\x80 \xEA\xB8\xB0\xEB\xB3\xB8 \xEA\xB3\xB5\xEC\x9C\xA0 (\xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80+\xEC\x95\x88\xEB\x82\xB4\xEB\xAC\xB8 \xEB\x93\xB1)</span>\n              </button>\n              <div style=\"display:flex; gap:8px;\">\n                <button type=\"button\" onclick=\"downloadBankCardImage()\" id=\"downloadBankCardBtn\" style=\"flex:1; background:#f1f5f9; color:#334155; border:1px solid #cbd5e1; padding:12px; border-radius:10px; font-size:13px; font-weight:800; cursor:pointer; display:flex; justify-content:center; align-items:center; gap:6px;\">\n                  <span>\xF0\x9F\x92\xBE \xEA\xB0\xA4\xEB\x9F\xAC\xEB\xA6\xAC/\xEC\x82\xAC\xEC\xA7\x84\xEC\xB2\xA9 \xEC\xA0\x80\xEC\x9E\xA5</span>\n                </button>\n                <button type=\"button\" onclick=\"copyBankCardText()\" id=\"copyBankCardTextBtn\" style=\"flex:1; background:#f1f5f9; color:#334155; border:1px solid #cbd5e1; padding:12px; border-radius:10px; font-size:13px; font-weight:800; cursor:pointer; display:flex; justify-content:center; align-items:center; gap:6px;\">\n                  <span>\xF0\x9F\x93\x8B \xED\x85\x8D\xEC\x8A\xA4\xED\x8A\xB8\xEB\xA7\x8C \xEB\xB3\xB5\xEC\x82\xAC</span>\n                </button>\n              </div>\n            </div>\n            <div id=\"cardShareStatus\" style=\"text-align:center; margin-top:12px; font-size:13px; font-weight:800; color:#10b981; display:none; background:#d1fae5; padding:8px; border-radius:8px;\">\n              \xE2\x9C\x85 \xEB\xAA\x85\xED\x95\xA8\xEC\x9D\xB4 \xEC\x84\xB1\xEA\xB3\xB5\xEC\xA0\x81\xEC\x9C\xBC\xEB\xA1\x9C \xEC\xA0\x84\xEC\x86\xA1/\xEB\xB3\xB5\xEC\x82\xAC \xEB\x90\x98\xEC\x97\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4!\n            </div>\n          </div>\n          \n          <!-- \xED\x94\x84\xEB\xA6\xAC\xEB\xAF\xB8\xEC\x97\x84 \xEB\xAA\x85\xED\x95\xA8 \xEC\x9E\x90\xEB\x8F\x99 \xEC\x83\x9D\xEC\x84\xB1\xEA\xB8\xB0 -->\n          <div style=\"background:#fdf4ff; border:1px solid #f5d0fe; border-radius:16px; padding:16px; margin-bottom:20px; box-shadow:0 4px 12px rgba(217,70,239,0.1);\">\n            <div style=\"display:flex; justify-content:space-between; align-items:center; margin-bottom:12px;\">\n              <div style=\"font-size:15px; font-weight:900; color:#a21caf; display:flex; align-items:center; gap:6px;\">\n                \xE2\x9C\xA8 \xED\x94\x84\xEB\xA6\xAC\xEB\xAF\xB8\xEC\x97\x84 \xEB\xAA\x85\xED\x95\xA8 \xEC\x9E\x90\xEB\x8F\x99 \xEC\x83\x9D\xEC\x84\xB1\xEA\xB8\xB0\n              </div>\n              <span style=\"background:#fce7f3; color:#be185d; font-size:10px; font-weight:900; padding:4px 8px; border-radius:99px;\">PREMIUM \xF0\x9F\x91\x91</span>\n            </div>\n            \n            ".freeze




































;  if current_user.premium? ; _erbout.<< "\n              <div style=\"font-size:12px; color:#c026d3; font-weight:600; margin-bottom:16px; line-height:1.5;\">\n                \xEC\xA7\x81\xED\x95\xA8 \xEB\x93\xB1 \xEC\xA0\x95\xEB\xB3\xB4\xEB\xA7\x8C \xEC\x9E\x85\xEB\xA0\xA5\xED\x95\x98\xEB\xA9\xB4 \xEC\x9D\xB8\xEC\x87\x84\xEC\x86\x8C \xEB\xB6\x80\xEB\x9F\xBD\xEC\xA7\x80 \xEC\x95\x8A\xEC\x9D\x80 \xEC\x84\xB8\xEB\xA0\xA8\xEB\x90\x9C \xEB\xAA\x85\xED\x95\xA8\xEC\x9D\xB4 \xEB\x9A\x9D\xEB\x94\xB1! \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80\xEB\xA5\xBC \xEB\x8B\xA4\xEC\x9A\xB4\xEB\xB0\x9B\xEC\x95\x84 \xEC\xB9\xB4\xED\x86\xA1\xEC\x9C\xBC\xEB\xA1\x9C \xEB\x82\x98\xEB\x88\xA0\xEC\xA3\xBC\xEC\x84\xB8\xEC\x9A\x94.\n              </div>\n              <!-- \xEC\x9E\x85\xEB\xA0\xA5 \xED\x8F\xBC -->\n              <div style=\"display:grid; grid-template-columns:1fr; gap:10px; margin-bottom:16px;\">\n                <input type=\"text\" id=\"bcTeamInput\" placeholder=\"\xEC\x97\x85\xEC\xB2\xB4\xEB\xAA\x85 (\xEC\x98\x88: \xEC\x97\x85\xEC\xB2\xB4\xEB\xAA\x85)\" style=\"width:100%; padding:14px; border-radius:12px; border:1px solid #cbd5e1; font-weight:800; font-size:14px; color:#1e293b;\" value=\"".freeze





; _erbout.<<(( current_user.team_name ).to_s); _erbout.<< "\">\n                <input type=\"text\" id=\"bcRoleInput\" placeholder=\"\xEC\xA7\x81\xEC\xB1\x85 (\xEC\x98\x88: \xEC\xA7\x81\xEC\xB1\x85)\" style=\"width:100%; padding:14px; border-radius:12px; border:1px solid #cbd5e1; font-weight:800; font-size:14px; color:#1e293b;\" value=\"".freeze
; _erbout.<<(( current_user.role ).to_s); _erbout.<< "\">\n                <input type=\"text\" id=\"bcNameInput\" placeholder=\"\xEC\x84\xB1\xED\x95\xA8 (\xEC\x98\x88: \xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC)\" style=\"width:100%; padding:14px; border-radius:12px; border:1px solid #cbd5e1; font-weight:800; font-size:14px; color:#1e293b;\" value=\"".freeze
; _erbout.<<(( current_user.name.to_s.match?(/^[a-z0-9]{10}$/) ? '' : current_user.name ).to_s); _erbout.<< "\">\n                <input type=\"text\" id=\"bcPhoneInput\" placeholder=\"\xEC\xA0\x84\xED\x99\x94\xEB\xB2\x88\xED\x98\xB8 (\xEC\x98\x88: 010-1234-5678)\" style=\"width:100%; padding:14px; border-radius:12px; border:1px solid #cbd5e1; font-weight:800; font-size:14px; color:#1e293b;\" value=\"".freeze
; _erbout.<<(( current_user.phone ).to_s); _erbout.<< "\">\n              </div>\n\n              <!-- \xED\x85\x9C\xED\x94\x8C\xEB\xA6\xBF \xEC\x84\xA0\xED\x83\x9D -->\n              <div style=\"display:flex; gap:8px; margin-bottom:16px;\">\n                <button type=\"button\" onclick=\"setBcTemplate('A')\" id=\"btnTplA\" style=\"flex:1; padding:10px; background:#4c1d95; color:white; border:none; border-radius:8px; font-size:12px; font-weight:800; cursor:pointer; font-family:inherit;\">[\xEB\x8F\x84\xEC\x95\x88 A] \xEC\x8B\xA0\xEB\xA2\xB0\xEA\xB0\x90 \xED\x98\x84\xEC\x9E\xA5\xED\x98\x95</button>\n                <button type=\"button\" onclick=\"setBcTemplate('B')\" id=\"btnTplB\" style=\"flex:1; padding:10px; background:#f1f5f9; color:#475569; border:1px solid #cbd5e1; border-radius:8px; font-size:12px; font-weight:800; cursor:pointer; font-family:inherit;\">[\xEB\x8F\x84\xEC\x95\x88 B] \xEC\x84\xB8\xEB\xA0\xA8\xEB\x90\x9C \xEA\xB1\xB4\xEC\xB6\x95\xED\x98\x95</button>\n              </div>\n\n              <!-- Preview Card Container -->\n              <div id=\"bcPreviewWrap\" style=\"margin-bottom:16px;\">\n                <!-- Template A (\xED\x98\x84\xEC\x9E\xA5\xED\x98\x95) -->\n                <div id=\"bcTemplateA\" style=\"position:relative; width:100%; aspect-ratio:1.8; border-radius:10px; background:#111827; color:white; padding:24px; box-shadow:0 10px 25px rgba(0,0,0,0.15); box-sizing:border-box; overflow:hidden;\">\n                  <div style=\"position:absolute; top:0; left:0; width:8px; height:100%; background:#eab308;\"></div>\n                  <div style=\"display:flex; flex-direction:column; justify-content:space-between; height:100%; padding-left:12px;\">\n                    <div>\n                      <div id=\"bcA_Team\" style=\"font-size:15px; font-weight:900; color:#eab308; letter-spacing:1px; margin-bottom:4px;\">".freeze















; _erbout.<<(( current_user.team_name.presence || '업체명' ).to_s); _erbout.<< "</div>\n                    </div>\n                    <div style=\"margin-top:auto; margin-bottom:auto;\">\n                      <div style=\"display:flex; align-items:baseline; gap:8px; margin-bottom:8px;\">\n                        <div id=\"bcA_Name\" style=\"font-size:26px; font-weight:900; letter-spacing:2px;\">".freeze



; _erbout.<<(( current_user.name.presence || '일잘러' ).to_s); _erbout.<< "</div>\n                        <div id=\"bcA_Role\" style=\"font-size:15px; font-weight:700; color:#9ca3af;\">".freeze
; _erbout.<<(( current_user.role.presence || '직책' ).to_s); _erbout.<< "</div>\n                      </div>\n                    </div>\n                    <div style=\"display:flex; justify-content:space-between; align-items:flex-end;\">\n                      <div id=\"bcA_Phone\" style=\"font-size:16px; font-weight:800; letter-spacing:1px; color:#f3f4f6;\">".freeze



; _erbout.<<(( current_user.phone.presence || '010-1234-5678' ).to_s); _erbout.<< "</div>\n                      <div style=\"font-size:9px; font-weight:800; opacity:0.6; text-align:right;\">\xEC\x8A\xA4\xEB\xA7\x88\xED\x8A\xB8\xED\x95\x9C \xED\x98\x84\xEC\x9E\xA5 \xEA\xB4\x80\xEB\xA6\xAC<br>\xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC \xEC\x95\xB1</div>\n                    </div>\n                  </div>\n                </div>\n\n                <!-- Template B (\xEB\x94\x94\xEC\x9E\x90\xEC\x9D\xB8\xED\x98\x95) -->\n                <div id=\"bcTemplateB\" style=\"display:none; position:relative; width:100%; aspect-ratio:1.8; border-radius:10px; background:#ffffff; color:#111827; padding:24px; box-shadow:0 10px 25px rgba(0,0,0,0.05); box-sizing:border-box; overflow:hidden; border:1px solid #f1f5f9;\">\n                  <div style=\"position:absolute; bottom:-40px; right:-40px; width:150px; height:150px; border-radius:50%; background:#f8fafc; border:2px solid #f1f5f9;\"></div>\n                  <div style=\"position:relative; z-index:1; display:flex; flex-direction:column; justify-content:space-between; height:100%; text-align:right;\">\n                    <div>\n                      <div id=\"bcB_Team\" style=\"font-size:12px; font-weight:800; color:#64748b; letter-spacing:2px;\">".freeze










; _erbout.<<(( current_user.team_name.presence || '업체명' ).to_s); _erbout.<< "</div>\n                    </div>\n                    <div style=\"margin-top:auto; margin-bottom:auto; padding-right:10px; border-right:4px solid #111827;\">\n                      <div id=\"bcB_Name\" style=\"font-size:28px; font-weight:300; letter-spacing:-1px; color:#0f172a; margin-bottom:4px;\"><strong>".freeze


; _erbout.<<(( (current_user.name.presence || '일잘러').chars.first ).to_s); _erbout.<< "</strong>".freeze; _erbout.<<(( (current_user.name.presence || '일잘러').chars.drop(1).join ).to_s); _erbout.<< "</div>\n                      <div id=\"bcB_Role\" style=\"font-size:14px; font-weight:600; color:#475569;\">".freeze
; _erbout.<<(( current_user.role.presence || '직책' ).to_s); _erbout.<< "</div>\n                    </div>\n                    <div style=\"display:flex; justify-content:space-between; align-items:flex-end;\">\n                      <div style=\"font-size:9px; font-weight:800; color:#cbd5e1; text-align:left;\">\xEC\x8A\xA4\xEB\xA7\x88\xED\x8A\xB8\xED\x95\x9C \xED\x98\x84\xEC\x9E\xA5 \xEA\xB4\x80\xEB\xA6\xAC<br>\xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC \xEC\x95\xB1</div>\n                      <div id=\"bcB_Phone\" style=\"font-size:15px; font-weight:700; color:#334155;\">".freeze



; _erbout.<<(( current_user.phone.presence || '010-1234-5678' ).to_s); _erbout.<< "</div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n\n              <!-- Action Buttons -->\n              <div style=\"display:flex; flex-direction:column; gap:8px;\">\n                <button type=\"button\" onclick=\"generateAndShareBizCard()\" id=\"shareBizCardBtn\" style=\"width:100%; background:#c026d3; color:white; border:none; padding:16px; border-radius:12px; font-size:15px; font-weight:900; cursor:pointer; box-shadow:0 6px 16px rgba(192,38,211,0.3); display:flex; justify-content:center; align-items:center; gap:8px; transition:transform 0.1s; font-family:inherit;\">\n                  <span>\xF0\x9F\x9A\x80 \xEA\xB8\xB0\xEB\xB3\xB8 \xEA\xB3\xB5\xEC\x9C\xA0 (\xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80+\xEC\x95\x88\xEB\x82\xB4\xEB\xAC\xB8 \xEB\x93\xB1)</span>\n                </button>\n                <div style=\"display:flex; gap:8px;\">\n                  <button type=\"button\" onclick=\"downloadBizCardImage()\" id=\"downloadBizCardBtn\" style=\"flex:1; background:#fdf4ff; color:#a21caf; border:1px solid #f0abfc; padding:12px; border-radius:10px; font-size:13px; font-weight:800; cursor:pointer; display:flex; justify-content:center; align-items:center; gap:6px;\">\n                    <span>\xF0\x9F\x92\xBE \xEC\x82\xAC\xEC\xA7\x84\xEC\xB2\xA9(\xEC\x95\xA8\xEB\xB2\x94)\xEC\x97\x90 \xEC\xA0\x80\xEC\x9E\xA5</span>\n                  </button>\n                  <button type=\"button\" onclick=\"copyBizCardText()\" id=\"copyBizCardTextBtn\" style=\"flex:1; background:#fdf4ff; color:#a21caf; border:1px solid #f0abfc; padding:12px; border-radius:10px; font-size:13px; font-weight:800; cursor:pointer; display:flex; justify-content:center; align-items:center; gap:6px;\">\n                    <span>\xF0\x9F\x93\x8B \xED\x85\x8D\xEC\x8A\xA4\xED\x8A\xB8\xEB\xA7\x8C \xEB\xB3\xB5\xEC\x82\xAC</span>\n                  </button>\n                </div>\n              </div>\n              <div id=\"bcShareStatus\" style=\"text-align:center; margin-top:12px; font-size:13px; font-weight:800; color:#a21caf; display:none; background:#fdf4ff; padding:8px; border-radius:8px;\">\n                \xE2\x9C\x85 \xEB\xAA\x85\xED\x95\xA8\xEC\x9D\xB4 \xEC\x84\xB1\xEA\xB3\xB5\xEC\xA0\x81\xEC\x9C\xBC\xEB\xA1\x9C \xEC\xB6\x9C\xEB\xA0\xA5/\xEA\xB3\xB5\xEC\x9C\xA0 \xEB\x90\x98\xEC\x97\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4!\n              </div>\n\n            ".freeze























;  else ; _erbout.<< "\n              <!-- \xEB\xB9\x84\xED\x86\xB5\xEA\xB3\xBC \xEC\x9C\xA0\xEC\xA0\x80 \xEC\x97\x85\xEC\x85\x80 \xEB\xA9\x94\xEC\x8B\x9C\xEC\xA7\x80 -->\n              <div style=\"display:flex; flex-direction:column; align-items:center; padding:24px 16px; background:rgba(255,255,255,0.7); border-radius:12px; border:1px dashed #f0abfc;\">\n                <div style=\"font-size:32px; margin-bottom:12px; filter:grayscale(1) opacity(0.5);\">\xF0\x9F\xAA\xAA</div>\n                <div style=\"font-size:14px; font-weight:800; color:#86198f; text-align:center; margin-bottom:8px;\">\n                  \xED\x94\x84\xEB\xA6\xAC\xEB\xAF\xB8\xEC\x97\x84 \xEC\x9A\x94\xEA\xB8\x88\xEC\xA0\x9C\xEB\xA5\xBC \xEC\x9D\xB4\xEC\x9A\xA9\xED\x95\x98\xEA\xB3\xA0<br>\xEA\xB3\xA0\xEA\xB8\x89 \xEB\xAA\x85\xED\x95\xA8 2\xEC\xA2\x85\xEC\x9D\x84 \xED\x8F\x89\xEC\x83\x9D \xEB\xAC\xB4\xEB\xA3\x8C\xEB\xA1\x9C \xEC\xB0\x8D\xEC\x96\xB4\xEB\x82\xB4\xEC\x84\xB8\xEC\x9A\x94!\n                </div>\n                <div style=\"font-size:12px; color:#a21caf; text-align:center; margin-bottom:16px;\">\n                  \xEC\x9D\xB8\xEC\x87\x84\xEC\x86\x8C \xEA\xB0\x88 \xED\x95\x84\xEC\x9A\x94 \xEC\x97\x86\xEC\x9D\xB4 \xEC\xA6\x89\xEC\x8B\x9C \xEB\xB0\x9C\xEA\xB8\x89 \xEA\xB0\x80\xEB\x8A\xA5\xED\x95\x9C \xEA\xB3\xA0\xED\x92\x88\xEA\xB2\xA9 \xEB\xAA\x85\xED\x95\xA8.<br>\xEB\xAC\xB8\xEC\x9E\x90\xEB\x82\x98 \xEC\xB9\xB4\xED\x86\xA1 \xEC\xA0\x84\xEC\x86\xA1 \xEC\x8B\x9C \xEB\xB8\x8C\xEB\x9E\x9C\xEB\x93\x9C \xEA\xB0\x80\xEC\xB9\x98\xEA\xB0\x80 \xED\x99\x95 \xEC\x98\xAC\xEB\x9D\xBC\xEA\xB0\x91\xEB\x8B\x88\xEB\x8B\xA4.\n                </div>\n                ".freeze









; _erbout.<<(( link_to "👑 프리미엄 플랜 구독하기", subscriptions_path, style: "background:#86198f; color:white; padding:12px 24px; border-radius:8px; font-size:13px; font-weight:800; text-decoration:none;" ).to_s); _erbout.<< "\n              </div>\n            ".freeze

;  end ; _erbout.<< "\n          </div>\n\n          <div style=\"display:flex; flex-direction:column; gap:12px; margin-bottom:16px;\">\n            ".freeze



;  [
              { key: :business_card, label: '🪪 명함' },
              { key: :business_registration, label: '📜 사업자등록증' },
              { key: :bankbook_copy, label: '💰 일반 통장 사본' },
              { key: :business_bankbook_copy, label: '🏦 사업자 통장 사본' }
            ].each do |doc| ; _erbout.<< "\n              <div style=\"background:#f9fafb; border:1px solid #e5e7eb; border-radius:12px; padding:12px; display:flex; flex-direction:column; gap:12px;\">\n                <div style=\"display:flex; align-items:center; justify-content:space-between;\">\n                  <div>\n                    <div style=\"font-size:13px; font-weight:800; color:#374151;\">".freeze



; _erbout.<<(( doc[:label] ).to_s); _erbout.<< "</div>\n                    <div style=\"font-size:11px; color:#9ca3af; margin-top:2px;\">\n                      ".freeze

;  if current_user.public_send("#{doc[:key]}_b64").present? ; _erbout.<< "\n                        <span style=\"color:#10b981; font-weight:700;\">\xE2\x9C\x85 \xEB\x93\xB1\xEB\xA1\x9D\xEB\x90\xA8</span>\n                      ".freeze

;  else ; _erbout.<< "\n                        \xEB\xAF\xB8\xEB\x93\xB1\xEB\xA1\x9D\n                      ".freeze

;  end ; _erbout.<< "\n                    </div>\n                  </div>\n                  <div style=\"display:flex; align-items:center; gap:8px;\">\n                    ".freeze



; _erbout.<<(( f.file_field doc[:key], accept: "image/*", style: "font-size:12px; width:140px; color:#6b7280;", class: "auto-png-convert" ).to_s); _erbout.<< "\n                    \n                    ".freeze

;  if current_user.public_send("#{doc[:key]}_b64").present? ; _erbout.<< "\n                      <button type=\"button\" onclick=\"submitDeleteDocument('".freeze
; _erbout.<<(( doc[:key] ).to_s); _erbout.<< "')\" style=\"background:#ef4444; color:white; border:none; padding:6px 12px; border-radius:8px; font-size:12px; font-weight:800; display:inline-block; cursor:pointer;\">\xEC\x82\xAD\xEC\xA0\x9C</button>\n                    ".freeze
;  end ; _erbout.<< "\n                  </div>\n                </div>\n\n                ".freeze



;  if current_user.public_send("#{doc[:key]}_b64").present? ; _erbout.<< "\n                  <div style=\"width:100%; border-radius:8px; overflow:hidden; border:1px solid #e5e7eb; background:white;\">\n                    ".freeze

; _erbout.<<(( image_tag "data:image/png;base64,#{current_user.public_send("#{doc[:key]}_b64")}", style: "width:100%; height:auto; display:block;", alt: doc[:label] ).to_s); _erbout.<< "\n                  </div>\n                ".freeze

;  end ; _erbout.<< "\n              </div>\n            ".freeze

;  end ; _erbout.<< "\n          </div>\n          \n          <div style=\"display:flex; gap:8px;\">\n            ".freeze



; _erbout.<<(( f.submit "서류 저장/업데이트", style: "flex:1; background:#2563eb; color:white; border:none; padding:16px; border-radius:14px; font-size:14px; font-weight:800; cursor:pointer;" ).to_s); _erbout.<< "\n            \n            ".freeze

;  if current_user.document_share_token.present? ; _erbout.<< "\n              <button type=\"button\" onclick=\"document.getElementById('shareModal').style.display='flex';\" style=\"flex:1; background:linear-gradient(135deg, #10b981, #059669); color:white; border:none; padding:16px; border-radius:14px; font-size:14px; font-weight:800; cursor:pointer; box-shadow:0 4px 12px rgba(16,185,129,0.3);\">\n                \xF0\x9F\x94\x97 \xEB\xAC\xB8\xEC\x9E\x90\xEB\xA1\x9C \xEB\xB3\xB5\xEC\x82\xAC\xC2\xB7\xEA\xB3\xB5\xEC\x9C\xA0\n              </button>\n            ".freeze



;  end ; _erbout.<< "\n          </div>\n        ".freeze

;  end ; _erbout.<< "\n\n        ".freeze

;  if current_user.document_share_token.present? ; _erbout.<< "\n          <!-- \xEA\xB3\xB5\xEC\x9C\xA0 \xEC\x98\xB5\xEC\x85\x98 \xEB\xAA\xA8\xEB\x8B\xAC -->\n          <div id=\"shareModal\" style=\"display:none; position:fixed; top:0; left:0; right:0; bottom:0; background:rgba(0,0,0,0.5); z-index:9999; align-items:center; justify-content:center; padding:20px;\">\n            <div style=\"background:white; border-radius:24px; padding:24px; max-width:380px; width:100%; box-shadow:0 20px 60px rgba(0,0,0,0.3);\">\n              <div style=\"display:flex; justify-content:space-between; align-items:center; margin-bottom:16px;\">\n                <div style=\"font-size:18px; font-weight:900; color:#111827;\">\xF0\x9F\x93\xA8 \xEA\xB3\xB5\xEC\x9C\xA0\xED\x95\xA0 \xEC\x84\x9C\xEB\xA5\x98 \xEC\x84\xA0\xED\x83\x9D</div>\n                <button type=\"button\" onclick=\"document.getElementById('shareModal').style.display='none'\" style=\"background:none; border:none; font-size:20px; cursor:pointer; color:#9ca3af;\">&times;</button>\n              </div>\n              <div style=\"font-size:13px; color:#6b7280; font-weight:600; margin-bottom:20px; line-height:1.5;\">\n                \xEC\x83\x81\xEB\x8C\x80\xEB\xB0\xA9\xEC\x97\x90\xEA\xB2\x8C \xEB\xB3\xB4\xEB\x82\xBC \xED\x95\xAD\xEB\xAA\xA9\xEB\xA7\x8C \xEC\xB2\xB4\xED\x81\xAC\xED\x95\x98\xEC\x84\xB8\xEC\x9A\x94.\n              </div>\n              \n              <div style=\"display:flex; flex-direction:column; gap:12px; margin-bottom:24px;\">\n                <label for=\"check_card\" style=\"display:flex; align-items:center; gap:12px; font-size:15px; font-weight:700; color:#374151; cursor:pointer; padding:12px; background:#f9fafb; border-radius:12px; border:1px solid #e5e7eb; -webkit-tap-highlight-color: transparent;\">\n                  <input type=\"checkbox\" id=\"check_card\" value=\"card\" ".freeze













; _erbout.<<(( "checked" if current_user.business_card_b64.present? ).to_s); _erbout.<< " ".freeze; _erbout.<<(( "disabled" unless current_user.business_card_b64.present? ).to_s); _erbout.<< " style=\"appearance:checkbox; -webkit-appearance:checkbox; accent-color:#2563eb; width:22px; height:22px; cursor:pointer; margin:0;\">\n                  <span>\xF0\x9F\xAA\xAA \xEB\xAA\x85\xED\x95\xA8</span>\n                  ".freeze

; _erbout.<<(( '<span style="margin-left:auto; font-size:11px; color:#ef4444;">미등록</span>'.html_safe unless current_user.business_card_b64.present? ).to_s); _erbout.<< "\n                </label>\n                <label for=\"check_reg\" style=\"display:flex; align-items:center; gap:12px; font-size:15px; font-weight:700; color:#374151; cursor:pointer; padding:12px; background:#f9fafb; border-radius:12px; border:1px solid #e5e7eb; -webkit-tap-highlight-color: transparent;\">\n                  <input type=\"checkbox\" id=\"check_reg\" value=\"reg\" ".freeze


; _erbout.<<(( "checked" if current_user.business_registration_b64.present? ).to_s); _erbout.<< " ".freeze; _erbout.<<(( "disabled" unless current_user.business_registration_b64.present? ).to_s); _erbout.<< " style=\"appearance:checkbox; -webkit-appearance:checkbox; accent-color:#2563eb; width:22px; height:22px; cursor:pointer; margin:0;\">\n                  <span>\xF0\x9F\x93\x9C \xEC\x82\xAC\xEC\x97\x85\xEC\x9E\x90\xEB\x93\xB1\xEB\xA1\x9D\xEC\xA6\x9D</span>\n                  ".freeze

; _erbout.<<(( '<span style="margin-left:auto; font-size:11px; color:#ef4444;">미등록</span>'.html_safe unless current_user.business_registration_b64.present? ).to_s); _erbout.<< "\n                </label>\n                <label for=\"check_bank\" style=\"display:flex; align-items:center; gap:12px; font-size:15px; font-weight:700; color:#374151; cursor:pointer; padding:12px; background:#f9fafb; border-radius:12px; border:1px solid #e5e7eb; -webkit-tap-highlight-color: transparent;\">\n                  <input type=\"checkbox\" id=\"check_bank\" value=\"bank\" ".freeze


; _erbout.<<(( "checked" if current_user.bankbook_copy_b64.present? ).to_s); _erbout.<< " ".freeze; _erbout.<<(( "disabled" unless current_user.bankbook_copy_b64.present? ).to_s); _erbout.<< " style=\"appearance:checkbox; -webkit-appearance:checkbox; accent-color:#2563eb; width:22px; height:22px; cursor:pointer; margin:0;\">\n                  <span>\xF0\x9F\x92\xB0 \xEC\x9D\xBC\xEB\xB0\x98 \xED\x86\xB5\xEC\x9E\xA5 \xEC\x82\xAC\xEB\xB3\xB8</span>\n                  ".freeze

; _erbout.<<(( '<span style="margin-left:auto; font-size:11px; color:#ef4444;">미등록</span>'.html_safe unless current_user.bankbook_copy_b64.present? ).to_s); _erbout.<< "\n                </label>\n                <label for=\"check_biz_bank\" style=\"display:flex; align-items:center; gap:12px; font-size:15px; font-weight:700; color:#374151; cursor:pointer; padding:12px; background:#f9fafb; border-radius:12px; border:1px solid #e5e7eb; -webkit-tap-highlight-color: transparent;\">\n                  <input type=\"checkbox\" id=\"check_biz_bank\" value=\"biz_bank\" ".freeze


; _erbout.<<(( "checked" if current_user.business_bankbook_copy_b64.present? ).to_s); _erbout.<< " ".freeze; _erbout.<<(( "disabled" unless current_user.business_bankbook_copy_b64.present? ).to_s); _erbout.<< " style=\"appearance:checkbox; -webkit-appearance:checkbox; accent-color:#2563eb; width:22px; height:22px; cursor:pointer; margin:0;\">\n                  <span>\xF0\x9F\x8F\xA6 \xEC\x82\xAC\xEC\x97\x85\xEC\x9E\x90 \xED\x86\xB5\xEC\x9E\xA5 \xEC\x82\xAC\xEB\xB3\xB8</span>\n                  ".freeze

; _erbout.<<(( '<span style="margin-left:auto; font-size:11px; color:#ef4444;">미등록</span>'.html_safe unless current_user.business_bankbook_copy_b64.present? ).to_s); _erbout.<< "\n                </label>\n              </div>\n              \n              <button type=\"button\" onclick=\"executeShare('".freeze



; _erbout.<<(( current_user.document_share_token ).to_s); _erbout.<< "')\" style=\"width:100%; padding:14px; background:#2563eb; color:white; border:none; border-radius:14px; font-size:15px; font-weight:900; cursor:pointer; font-family:inherit;\">\n                \xEC\x84\xA0\xED\x83\x9D\xED\x95\x9C \xEC\x84\x9C\xEB\xA5\x98 \xEB\xA7\x81\xED\x81\xAC \xEB\xB3\xB5\xEC\x82\xAC\n              </button>\n            </div>\n          </div>\n          \n            <script>\n            function showShareSuccess() {\n              const toast = document.getElementById('shareSuccessToast');\n              if (toast) {\n                toast.style.display = 'flex';\n                toast.style.opacity = '1';\n                setTimeout(() => {\n                  toast.style.opacity = '0';\n                  setTimeout(() => { toast.style.display = 'none'; }, 300);\n                }, 2000);\n              }\n            }\n\n            function executeShare(token) {\n              const selectedKeys = [];\n              const selectedNames = [];\n              \n              if (document.getElementById('check_card').checked) { selectedKeys.push('card'); selectedNames.push('\xEB\xAA\x85\xED\x95\xA8'); }\n              if (document.getElementById('check_reg').checked) { selectedKeys.push('reg'); selectedNames.push('\xEC\x82\xAC\xEC\x97\x85\xEC\x9E\x90\xEB\x93\xB1\xEB\xA1\x9D\xEC\xA6\x9D'); }\n              if (document.getElementById('check_bank').checked) { selectedKeys.push('bank'); selectedNames.push('\xEC\x9D\xBC\xEB\xB0\x98\xED\x86\xB5\xEC\x9E\xA5'); }\n              if (document.getElementById('check_biz_bank').checked) { selectedKeys.push('biz_bank'); selectedNames.push('\xEC\x82\xAC\xEC\x97\x85\xEC\x9E\x90\xED\x86\xB5\xEC\x9E\xA5'); }\n              \n              if (selectedKeys.length === 0) {\n                alert(\"\xEA\xB3\xB5\xEC\x9C\xA0\xED\x95\xA0 \xEC\x84\x9C\xEB\xA5\x98\xEB\xA5\xBC 1\xEA\xB0\x9C \xEC\x9D\xB4\xEC\x83\x81 \xEC\x84\xA0\xED\x83\x9D\xED\x95\xB4\xEC\xA3\xBC\xEC\x84\xB8\xEC\x9A\x94.\");\n                return;\n              }\n              \n              const shareUrl = 'https://www.workgood.co.kr/d/' + token + '?docs=' + selectedKeys.join(',') + '&v=4';\n              const dynamicText = '\xEC\x95\x88\xEB\x85\x95\xED\x95\x98\xEC\x84\xB8\xEC\x9A\x94, \xEC\x9A\x94\xEC\xB2\xAD\xED\x95\x98\xEC\x8B\xA0 ' + selectedNames.join(', ') + ' \xEB\xB3\xB4\xEB\x82\xB4\xEB\x93\x9C\xEB\xA6\xBD\xEB\x8B\x88\xEB\x8B\xA4.';\n              \n              if (navigator.share) {\n                navigator.share({\n                  title: '\xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC - \xEC\x84\x9C\xEB\xA5\x98 \xEC\x95\x88\xEB\x82\xB4',\n                  text: dynamicText,\n                  url: shareUrl\n                }).then(() => {\n                  document.getElementById('shareModal').style.display='none';\n                  showShareSuccess();\n                }).catch((e) => {});\n              } else if (navigator.clipboard) {\n                navigator.clipboard.writeText(dynamicText + '\\n' + shareUrl).then(() => {\n                  document.getElementById('shareModal').style.display='none';\n                  showShareSuccess();\n                });\n              } else {\n                alert(\"\xEA\xB3\xB5\xEC\x9C\xA0 \xEA\xB8\xB0\xEB\x8A\xA5\xEC\x9D\xB4 \xEC\xA7\x80\xEC\x9B\x90\xEB\x90\x98\xEC\xA7\x80 \xEC\x95\x8A\xEB\x8A\x94 \xEB\xB8\x8C\xEB\x9D\xBC\xEC\x9A\xB0\xEC\xA0\x80\xEC\x9E\x85\xEB\x8B\x88\xEB\x8B\xA4.\");\n              }\n            }\n          </script>\n\n          <!-- Share Success Toast Overlay -->\n          <div id=\"shareSuccessToast\" style=\"display:none; position:fixed; top:50%; left:50%; transform:translate(-50%, -50%); background:rgba(17, 24, 39, 0.9); color:white; padding:24px 32px; border-radius:20px; z-index:10000; flex-direction:column; align-items:center; opacity:0; transition:opacity 0.3s ease; box-shadow:0 20px 40px rgba(0,0,0,0.2);\">\n            <div style=\"font-size:48px; margin-bottom:12px;\">\xE2\x9C\x85</div>\n            <div style=\"font-size:16px; font-weight:900;\">\xEA\xB3\xB5\xEC\x9C\xA0\xEA\xB0\x80 \xEC\x99\x84\xEB\xA3\x8C\xEB\x90\x98\xEC\x97\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4!</div>\n          </div>\n        ".freeze




























































;  end ; _erbout.<< "\n    </div>\n  </div>\n\n  <script src=\"https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js\"></script>\n  <script>\n    // \xED\x86\xB5\xEC\x9E\xA5 \xEB\xAA\x85\xED\x95\xA8 \xEC\x8B\xA4\xEC\x8B\x9C\xEA\xB0\x84 \xEC\x83\x9D\xEC\x84\xB1 \xEB\xA1\x9C\xEC\xA7\x81\n    document.addEventListener(\"turbo:load\", function() {\n      const bankColors = {\n        '\xEC\x8B\xA0\xED\x95\x9C\xEC\x9D\x80\xED\x96\x89': ['#0046FF', '#002E9D', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEA\xB5\xAD\xEB\xAF\xBC\xEC\x9D\x80\xED\x96\x89': ['#FFCC00', '#F5A623', '#334155', 'none'],\n        '\xEC\x9A\xB0\xEB\xA6\xAC\xEC\x9D\x80\xED\x96\x89': ['#0067AC', '#004B80', 'white', 'rgba(0,0,0,0.2)'],\n        '\xED\x95\x98\xEB\x82\x98\xEC\x9D\x80\xED\x96\x89': ['#008485', '#00595A', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEB\x86\x8D\xED\x98\x91\xEC\x9D\x80\xED\x96\x89': ['#008D62', '#005C40', 'white', 'rgba(0,0,0,0.2)'],\n        'IBK\xEA\xB8\xB0\xEC\x97\x85\xEC\x9D\x80\xED\x96\x89': ['#1B4D98', '#113366', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEA\xB8\xB0\xEC\x97\x85\xEC\x9D\x80\xED\x96\x89': ['#1B4D98', '#113366', 'white', 'rgba(0,0,0,0.2)'],\n        'KDB\xEC\x82\xB0\xEC\x97\x85\xEC\x9D\x80\xED\x96\x89': ['#0033A1', '#00226D', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEC\x88\x98\xED\x98\x91\xEC\x9D\x80\xED\x96\x89': ['#0082C5', '#005988', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEC\xB9\xB4\xEC\xB9\xB4\xEC\x98\xA4\xEB\xB1\x85\xED\x81\xAC': ['#FEE500', '#E5CE00', '#111827', 'none'],\n        '\xED\x86\xA0\xEC\x8A\xA4\xEB\xB1\x85\xED\x81\xAC': ['#3182F6', '#1E4DB7', 'white', 'rgba(0,0,0,0.1)'],\n        '\xEC\xBC\x80\xEC\x9D\xB4\xEB\xB1\x85\xED\x81\xAC': ['#000000', '#222222', 'white', 'none'],\n        '\xEC\x83\x88\xEB\xA7\x88\xEC\x9D\x84\xEA\xB8\x88\xEA\xB3\xA0': ['#116238', '#0A3D22', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEC\x9A\xB0\xEC\xB2\xB4\xEA\xB5\xAD': ['#FF4A00', '#CC3B00', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEC\x8B\xA0\xED\x98\x91': ['#005AAA', '#003D73', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEC\xA0\x80\xEC\xB6\x95\xEC\x9D\x80\xED\x96\x89': ['#E74C3C', '#C0392B', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEC\x82\xB0\xEB\xA6\xBC\xEC\xA1\xB0\xED\x95\xA9': ['#27AE60', '#1D8348', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEC\x94\xA8\xED\x8B\xB0\xEC\x9D\x80\xED\x96\x89': ['#002B49', '#00192A', 'white', 'rgba(0,0,0,0.2)'],\n        'SC\xEC\xA0\x9C\xEC\x9D\xBC\xEC\x9D\x80\xED\x96\x89': ['#5B2B82', '#3D1B57', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEB\x8C\x80\xEA\xB5\xAC\xEC\x9D\x80\xED\x96\x89': ['#008B3E', '#005F2B', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEB\xB6\x80\xEC\x82\xB0\xEC\x9D\x80\xED\x96\x89': ['#D51820', '#A91119', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEA\xB4\x91\xEC\xA3\xBC\xEC\x9D\x80\xED\x96\x89': ['#FFB600', '#D69800', '#111827', 'none'],\n        '\xEC\xA0\x9C\xEC\xA3\xBC\xEC\x9D\x80\xED\x96\x89': ['#003F98', '#002A67', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEC\xA0\x84\xEB\xB6\x81\xEC\x9D\x80\xED\x96\x89': ['#12285E', '#0B183A', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEA\xB2\xBD\xEB\x82\xA8\xEC\x9D\x80\xED\x96\x89': ['#ED1C24', '#BB131A', 'white', 'rgba(0,0,0,0.2)'],\n        '\xEA\xB8\xB0\xED\x83\x80': ['#475569', '#1e293b', 'white', 'rgba(0,0,0,0.2)']\n      };\n\n      const nameInput = document.getElementById('bankNameInput');\n      const accountInput = document.getElementById('bankAccountInput');\n      const holderInput = document.getElementById('bankHolderInput');\n      const cardEl = document.getElementById('bankCardElement');\n      \n      function updateCard() {\n        if(!cardEl || !nameInput) return;\n        const bName = nameInput.value || '\xEC\x8B\xA0\xED\x95\x9C\xEC\x9D\x80\xED\x96\x89';\n        const colors = bankColors[bName] || bankColors['\xEA\xB8\xB0\xED\x83\x80'];\n        \n        document.getElementById('cardBankName').textContent = nameInput.value || '\xEC\x9D\x80\xED\x96\x89\xEB\xAA\x85';\n        document.getElementById('cardAccountNumber').textContent = accountInput.value || '110-123-456789';\n        document.getElementById('cardHolderName').textContent = holderInput.value || '\xEA\xB9\x80\xEC\x9D\xBC\xEC\x9E\x98';\n\n        cardEl.style.background = `linear-gradient(135deg, ${colors[0]}, ${colors[1]})`;\n        cardEl.style.color = colors[2];\n        document.getElementById('cardAccountNumber').style.textShadow = colors[3];\n      }\n\n      if(nameInput) {\n        nameInput.addEventListener('change', updateCard);\n        accountInput.addEventListener('input', updateCard);\n        holderInput.addEventListener('input', updateCard);\n        updateCard(); // \xEC\xB4\x88\xEA\xB8\xB0\xED\x99\x94\n      }\n    });\n\n    async function generateAndShareBankCard() {\n      const btn = document.getElementById('shareBankCardBtn');\n      const status = document.getElementById('cardShareStatus');\n      const cardEl = document.getElementById('bankCardElement');\n      const bankName = document.getElementById('bankNameInput').value;\n      const bankAcc = document.getElementById('bankAccountInput').value;\n      const bankHolder = document.getElementById('bankHolderInput').value;\n\n      if (!bankName || !bankAcc) {\n        alert(\"\xEC\x9D\x80\xED\x96\x89\xEB\xAA\x85\xEA\xB3\xBC \xEA\xB3\x84\xEC\xA2\x8C\xEB\xB2\x88\xED\x98\xB8\xEB\xA5\xBC \xEB\xA8\xBC\xEC\xA0\x80 \xEC\x9E\x85\xEB\xA0\xA5\xED\x95\xB4\xEC\xA3\xBC\xEC\x84\xB8\xEC\x9A\x94.\");\n        if(!bankName) document.getElementById('bankNameInput').focus();\n        else document.getElementById('bankAccountInput').focus();\n        return;\n      }\n\n      // \xEA\xB3\xB5\xEC\x9C\xA0 \xEC\xA0\x84 \xED\x8F\xBC \xEC\x9E\x90\xEB\x8F\x99 \xEC\xA0\x80\xEC\x9E\xA5 \xED\x8A\xB8\xEB\xA6\xAC\xEA\xB1\xB0\n      const updateForm = btn.closest('form');\n      if (updateForm) {\n        const formData = new FormData(updateForm);\n        fetch(updateForm.action, {\n          method: updateForm.method.toUpperCase(),\n          body: formData,\n          headers: { 'Accept': 'text/vnd.turbo-stream.html, text/html' }\n        });\n      }\n\n      btn.disabled = true;\n      const originalText = btn.innerHTML;\n      btn.innerHTML = '\xE2\x8F\xB3 \xEB\xAA\x85\xED\x95\xA8 \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80 \xEA\xB5\xAC\xEC\x9B\x8C\xEB\x82\xB4\xEB\x8A\x94 \xEC\xA4\x91...';\n      btn.style.transform = 'scale(0.98)';\n\n      try {\n        const canvas = await html2canvas(cardEl, {\n          scale: 4, \n          backgroundColor: null,\n          logging: false\n        });\n\n        canvas.toBlob(async function(blob) {\n          const file = new File([blob], 'bank_card.png', { type: 'image/png' });\n          const textMsg = `[\xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC \xEC\xA0\x95\xEC\x82\xB0 \xEA\xB3\x84\xEC\xA2\x8C\xEC\x95\x88\xEB\x82\xB4]\\n${bankName} ${bankAcc} ${bankHolder}`;\n\n          if (navigator.canShare && navigator.canShare({ files: [file] })) {\n            await navigator.share({\n              title: '\xEA\xB2\xB0\xEC\xA0\x9C \xEA\xB3\x84\xEC\xA2\x8C \xEC\x95\x88\xEB\x82\xB4',\n              text: textMsg,\n              files: [file]\n            });\n            showSuccess();\n          } else if (navigator.share) {\n            await navigator.share({\n              title: '\xEA\xB2\xB0\xEC\xA0\x9C \xEA\xB3\x84\xEC\xA2\x8C \xEC\x95\x88\xEB\x82\xB4',\n              text: textMsg\n            });\n            showSuccess();\n          } else {\n             navigator.clipboard.writeText(textMsg);\n             const url = URL.createObjectURL(blob);\n             const a = document.createElement('a');\n             a.href = url;\n             a.download = 'bank_card.png';\n             a.click();\n             alert(\"\xEA\xB3\x84\xEC\xA2\x8C \xEC\xA0\x95\xEB\xB3\xB4\xEA\xB0\x80 \xED\x81\xB4\xEB\xA6\xBD\xEB\xB3\xB4\xEB\x93\x9C\xEC\x97\x90 \xEB\xB3\xB5\xEC\x82\xAC\xEB\x90\x98\xEC\x97\x88\xEA\xB3\xA0 \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80\xEA\xB0\x80 \xEB\x8B\xA4\xEC\x9A\xB4\xEB\xA1\x9C\xEB\x93\x9C \xEB\x90\x98\xEC\x97\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4.\");\n             showSuccess();\n          }\n        }, 'image/png', 1.0);\n      } catch (e) {\n        alert(\"\xEC\x9D\xBC\xEC\x8B\x9C\xEC\xA0\x81\xEC\x9D\xB8 \xEC\x98\xA4\xEB\xA5\x98\xEB\xA1\x9C \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80\xEB\xA5\xBC \xEC\x83\x9D\xEC\x84\xB1\xED\x95\x98\xEC\xA7\x80 \xEB\xAA\xBB\xED\x96\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4.\");\n      } finally {\n        setTimeout(() => {\n          btn.disabled = false;\n          btn.innerHTML = originalText;\n          btn.style.transform = 'scale(1)';\n        }, 800);\n      }\n\n      function showSuccess() {\n        status.style.display = 'block';\n        setTimeout(() => { status.style.display = 'none'; }, 5000);\n      }\n    }\n\n    let currentBcTemplate = 'A';\n    \n    function setBcTemplate(type) {\n      currentBcTemplate = type;\n      if(type === 'A') {\n        document.getElementById('bcTemplateA').style.display = 'block';\n        document.getElementById('bcTemplateB').style.display = 'none';\n        document.getElementById('btnTplA').style.background = '#4c1d95';\n        document.getElementById('btnTplA').style.color = 'white';\n        document.getElementById('btnTplA').style.border = 'none';\n        \n        document.getElementById('btnTplB').style.background = '#f1f5f9';\n        document.getElementById('btnTplB').style.color = '#475569';\n        document.getElementById('btnTplB').style.border = '1px solid #cbd5e1';\n      } else {\n        document.getElementById('bcTemplateA').style.display = 'none';\n        document.getElementById('bcTemplateB').style.display = 'block';\n        \n        document.getElementById('btnTplB').style.background = '#4c1d95';\n        document.getElementById('btnTplB').style.color = 'white';\n        document.getElementById('btnTplB').style.border = 'none';\n        \n        document.getElementById('btnTplA').style.background = '#f1f5f9';\n        document.getElementById('btnTplA').style.color = '#475569';\n        document.getElementById('btnTplA').style.border = '1px solid #cbd5e1';\n      }\n    }\n\n    document.addEventListener(\"turbo:load\", function() {\n      const bTeamInfo = document.getElementById('bcTeamInput');\n      const bRoleInfo = document.getElementById('bcRoleInput');\n      const bNameInfo = document.getElementById('bcNameInput');\n      const bPhoneInfo = document.getElementById('bcPhoneInput');\n      \n      function updateBizCard() {\n        if(!bTeamInfo) return;\n        \n        document.getElementById('bcA_Team').textContent = bTeamInfo.value || '\xEC\x97\x85\xEC\xB2\xB4\xEB\xAA\x85';\n        document.getElementById('bcB_Team').textContent = bTeamInfo.value || '\xEC\x97\x85\xEC\xB2\xB4\xEB\xAA\x85';\n        \n        document.getElementById('bcA_Role').textContent = bRoleInfo.value || '\xEC\xA7\x81\xEC\xB1\x85';\n        document.getElementById('bcB_Role').textContent = bRoleInfo.value || '\xEC\xA7\x81\xEC\xB1\x85';\n        \n        const nameVal = bNameInfo.value || '\xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC';\n        document.getElementById('bcA_Name').textContent = nameVal;\n        \n        if(nameVal.length >= 2) {\n          const firstChar = nameVal.substring(0, 1);\n          const restChar = nameVal.substring(1);\n          document.getElementById('bcB_Name').innerHTML = '<strong>' + firstChar + '</strong>' + restChar;\n        } else {\n          document.getElementById('bcB_Name').innerHTML = '<strong>' + nameVal + '</strong>';\n        }\n        \n        document.getElementById('bcA_Phone').textContent = bPhoneInfo.value || '010-1234-5678';\n        document.getElementById('bcB_Phone').textContent = bPhoneInfo.value || '010-1234-5678';\n      }\n\n      if(bTeamInfo) {\n        bTeamInfo.addEventListener('input', updateBizCard);\n        bRoleInfo.addEventListener('input', updateBizCard);\n        bNameInfo.addEventListener('input', updateBizCard);\n        bPhoneInfo.addEventListener('input', updateBizCard);\n        updateBizCard();\n      }\n    });\n\n    async function generateAndShareBizCard() {\n      const btn = document.getElementById('shareBizCardBtn');\n      const status = document.getElementById('bcShareStatus');\n      const cardEl = document.getElementById('bcTemplate' + currentBcTemplate);\n      \n      const tName = document.getElementById('bcNameInput').value;\n      const tRole = document.getElementById('bcRoleInput').value;\n      const tPhone = document.getElementById('bcPhoneInput').value;\n\n      btn.disabled = true;\n      const originalText = btn.innerHTML;\n      btn.innerHTML = '\xE2\x8F\xB3 \xEB\xAA\x85\xED\x95\xA8 \xEC\xA0\x9C\xEC\x9E\x91\xEC\x86\x8C \xEC\x9E\x90\xEB\x8F\x99 \xEC\xB6\x9C\xEB\xA0\xA5 \xEC\xA4\x91...';\n      btn.style.transform = 'scale(0.98)';\n\n      try {\n        const canvas = await html2canvas(cardEl, {\n          scale: 4, \n          backgroundColor: currentBcTemplate === 'A' ? '#111827' : '#ffffff',\n          logging: false\n        });\n\n        canvas.toBlob(async function(blob) {\n          const file = new File([blob], 'biz_card.png', { type: 'image/png' });\n          const textMsg = `[\xED\x98\x84\xEC\x9E\xA5 \xEC\xA0\x84\xEB\xAC\xB8\xEA\xB0\x80 \xEB\xAA\x85\xED\x95\xA8]\\n\xEC\x9D\xB4\xEB\xA6\x84: ${tName}\\n\xEC\xA7\x81\xED\x95\xA8: ${tRole}\\n\xEC\xA0\x84\xED\x99\x94: ${tPhone}`;\n\n          if (navigator.canShare && navigator.canShare({ files: [file] })) {\n            await navigator.share({\n              title: '\xEB\xAA\xA8\xEB\xB0\x94\xEC\x9D\xBC \xEB\xAA\x85\xED\x95\xA8',\n              text: textMsg,\n              files: [file]\n            });\n            showSuccess();\n          } else if (navigator.share) {\n            await navigator.share({\n              title: '\xEB\xAA\xA8\xEB\xB0\x94\xEC\x9D\xBC \xEB\xAA\x85\xED\x95\xA8',\n              text: textMsg\n            });\n            showSuccess();\n          } else {\n             navigator.clipboard.writeText(textMsg);\n             const url = URL.createObjectURL(blob);\n             const a = document.createElement('a');\n             a.href = url;\n             a.download = 'biz_card.png';\n             a.click();\n             alert(\"\xEB\xAA\x85\xED\x95\xA8 \xEC\xA0\x95\xEB\xB3\xB4\xEA\xB0\x80 \xEB\xB3\xB5\xEC\x82\xAC\xEB\x90\x98\xEC\x97\x88\xEA\xB3\xA0 \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80\xEA\xB0\x80 \xEB\x8B\xA4\xEC\x9A\xB4\xEB\xA1\x9C\xEB\x93\x9C \xEB\x90\x98\xEC\x97\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4.\");\n             showSuccess();\n          }\n        }, 'image/png', 1.0);\n      } catch (e) {\n        alert(\"\xEC\x9D\xBC\xEC\x8B\x9C\xEC\xA0\x81\xEC\x9D\xB8 \xEC\x98\xA4\xEB\xA5\x98\xEB\xA1\x9C \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80\xEB\xA5\xBC \xEC\x83\x9D\xEC\x84\xB1\xED\x95\x98\xEC\xA7\x80 \xEB\xAA\xBB\xED\x96\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4.\");\n      } finally {\n        setTimeout(() => {\n          btn.disabled = false;\n          btn.innerHTML = originalText;\n          btn.style.transform = 'scale(1)';\n        }, 800);\n      }\n      \n      function showSuccess() {\n        status.style.display = 'block';\n        setTimeout(() => { status.style.display = 'none'; }, 5000);\n      }\n    }\n\n    async function showImageForDownload(cardEl, bgColor) {\n      document.getElementById('imageDownloadModal').style.display = 'flex';\n      document.getElementById('downloadedImagePreview').src = '';\n      try {\n        const canvas = await html2canvas(cardEl, { scale: 4, backgroundColor: bgColor, logging: false });\n        const imgData = canvas.toDataURL('image/png');\n        document.getElementById('downloadedImagePreview').src = imgData;\n      } catch(e) {\n        alert(\"\xEC\x9D\xBC\xEC\x8B\x9C\xEC\xA0\x81\xEC\x9D\xB8 \xEC\x98\xA4\xEB\xA5\x98\xEB\xA1\x9C \xEC\xA0\x80\xEC\x9E\xA5 \xED\x8C\x9D\xEC\x97\x85\xEC\x9D\x84 \xEC\x97\xB4\xEC\xA7\x80 \xEB\xAA\xBB\xED\x96\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4.\");\n        document.getElementById('imageDownloadModal').style.display = 'none';\n      }\n    }\n\n    async function downloadBankCardImage() {\n      const btn = document.getElementById('downloadBankCardBtn');\n      const cardEl = document.getElementById('bankCardElement');\n      btn.disabled = true;\n      const originalText = btn.innerHTML;\n      btn.innerHTML = '\xE2\x8F\xB3 \xEA\xB5\xBD\xEB\x8A\x94 \xEC\xA4\x91...';\n      \n      await showImageForDownload(cardEl, null);\n      \n      btn.disabled = false;\n      btn.innerHTML = originalText;\n    }\n\n    function copyBankCardText() {\n      const bankName = document.getElementById('bankNameInput').value;\n      const bankAcc = document.getElementById('bankAccountInput').value;\n      const bankHolder = document.getElementById('bankHolderInput').value;\n      if (!bankName || !bankAcc) {\n        alert(\"\xEC\x9D\x80\xED\x96\x89\xEB\xAA\x85\xEA\xB3\xBC \xEA\xB3\x84\xEC\xA2\x8C\xEB\xB2\x88\xED\x98\xB8\xEB\xA5\xBC \xEB\xA8\xBC\xEC\xA0\x80 \xEC\x9E\x85\xEB\xA0\xA5\xED\x95\xB4\xEC\xA3\xBC\xEC\x84\xB8\xEC\x9A\x94.\");\n        return;\n      }\n      const textMsg = `[\xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC \xEC\xA0\x95\xEC\x82\xB0 \xEA\xB3\x84\xEC\xA2\x8C\xEC\x95\x88\xEB\x82\xB4]\\n${bankName} ${bankAcc} ${bankHolder}`;\n      navigator.clipboard.writeText(textMsg).then(() => {\n        const status = document.getElementById('cardShareStatus');\n        if(status) {\n          status.innerHTML = '\xE2\x9C\x85 \xED\x85\x8D\xEC\x8A\xA4\xED\x8A\xB8\xEA\xB0\x80 \xEB\xB3\xB5\xEC\x82\xAC\xEB\x90\x98\xEC\x97\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4!';\n          status.style.display = 'block';\n          setTimeout(() => { status.style.display = 'none'; }, 5000);\n        }\n      });\n    }\n\n    async function downloadBizCardImage() {\n      const btn = document.getElementById('downloadBizCardBtn');\n      const cardEl = document.getElementById('bcTemplate' + currentBcTemplate);\n      btn.disabled = true;\n      const originalText = btn.innerHTML;\n      btn.innerHTML = '\xE2\x8F\xB3 \xEA\xB5\xBD\xEB\x8A\x94 \xEC\xA4\x91...';\n      \n      await showImageForDownload(cardEl, currentBcTemplate === 'A' ? '#111827' : '#ffffff');\n      \n      btn.disabled = false;\n      btn.innerHTML = originalText;\n    }\n\n    function copyBizCardText() {\n      const tName = document.getElementById('bcNameInput').value || '\xEC\x9D\xBC\xEC\x9E\x98\xEB\x9F\xAC';\n      const tRole = document.getElementById('bcRoleInput').value || '\xEC\xA7\x81\xEC\xB1\x85';\n      const tPhone = document.getElementById('bcPhoneInput').value || '010-1234-5678';\n      const textMsg = `[\xED\x98\x84\xEC\x9E\xA5 \xEC\xA0\x84\xEB\xAC\xB8\xEA\xB0\x80 \xEB\xAA\x85\xED\x95\xA8]\\n\xEC\x9D\xB4\xEB\xA6\x84: ${tName}\\n\xEC\xA7\x81\xED\x95\xA8: ${tRole}\\n\xEC\xA0\x84\xED\x99\x94: ${tPhone}`;\n      navigator.clipboard.writeText(textMsg).then(() => {\n        const status = document.getElementById('bcShareStatus');\n        if(status) {\n          status.innerHTML = '\xE2\x9C\x85 \xED\x85\x8D\xEC\x8A\xA4\xED\x8A\xB8\xEA\xB0\x80 \xEB\xB3\xB5\xEC\x82\xAC\xEB\x90\x98\xEC\x97\x88\xEC\x8A\xB5\xEB\x8B\x88\xEB\x8B\xA4!';\n          status.style.display = 'block';\n          setTimeout(() => { status.style.display = 'none'; }, 5000);\n        }\n      });\n    }\n  </script>\n\n  <script>\n    // \xED\x8C\x8C\xEC\x9D\xBC \xEC\x97\x85\xEB\xA1\x9C\xEB\x93\x9C \xEC\x8B\x9C \xEB\xB8\x8C\xEB\x9D\xBC\xEC\x9A\xB0\xEC\xA0\x80 \xEB\x8B\xA8\xEC\x97\x90\xEC\x84\x9C PNG\xEB\xA1\x9C \xEC\x9E\x90\xEB\x8F\x99 \xEB\xB3\x80\xED\x99\x98 \xEB\xB0\x8F \xEB\xA6\xAC\xEC\x82\xAC\xEC\x9D\xB4\xEC\xA7\x95\n    document.addEventListener(\"turbo:load\", function() {\n      setTimeout(function() {\n        document.querySelectorAll('.auto-png-convert').forEach(function(input) {\n          if(input.dataset.pngConvertBounded) return;\n          input.dataset.pngConvertBounded = \"true\";\n          \n          input.addEventListener('change', function(e) {\n            const file = e.target.files[0];\n            if (!file) return;\n            if (!file.type.startsWith('image/')) return;\n            \n            const submitBtn = input.closest('form').querySelector('input[type=\"submit\"]');\n            if (submitBtn) {\n              submitBtn.dataset.originalText = submitBtn.value;\n              submitBtn.value = \"\xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80 \xEB\xB3\x80\xED\x99\x98 \xEC\xA4\x91...\";\n              submitBtn.disabled = true;\n              submitBtn.style.opacity = '0.7';\n            }\n            \n            const img = new Image();\n            img.onload = function() {\n              const canvas = document.createElement('canvas');\n              let width = img.width;\n              let height = img.height;\n              const max = 1600;\n              \n              if (width > max || height > max) {\n                if (width > height) {\n                  height = Math.round(height * max / width);\n                  width = max;\n                } else {\n                  width = Math.round(width * max / height);\n                  height = max;\n                }\n              }\n              \n              canvas.width = width;\n              canvas.height = height;\n              const ctx = canvas.getContext('2d');\n              ctx.drawImage(img, 0, 0, width, height);\n              \n              canvas.toBlob(function(blob) {\n                const newFileName = file.name.replace(/\\.[^/.]+$/, \"\") + \".png\";\n                const newFile = new File([blob], newFileName, { type: \"image/png\" });\n                \n                const dt = new DataTransfer();\n                dt.items.add(newFile);\n                input.files = dt.files;\n                \n                if (submitBtn) {\n                  submitBtn.value = submitBtn.dataset.originalText;\n                  submitBtn.disabled = false;\n                  submitBtn.style.opacity = '1';\n                }\n              }, \"image/png\", 1.0);\n            };\n            img.onerror = function() {\n              if (submitBtn) {\n                submitBtn.value = submitBtn.dataset.originalText;\n                submitBtn.disabled = false;\n                submitBtn.style.opacity = '1';\n              }\n            };\n            img.src = URL.createObjectURL(file);\n          });\n        });\n      }, 100);\n    });\n    });\n  </script>\n\n  <!-- \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80 \xEB\x8B\xA4\xEC\x9A\xB4\xEB\xA1\x9C\xEB\x93\x9C\xEC\x9A\xA9 \xEB\xAA\xA8\xEB\x8B\xAC -->\n  <div id=\"imageDownloadModal\" style=\"display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.85); z-index:9999; justify-content:center; align-items:center; flex-direction:column;\">\n    <div style=\"background:white; padding:12px 20px; border-radius:12px; font-weight:800; font-size:15px; margin-bottom:16px; color:#1e293b; display:flex; flex-direction:column; align-items:center; gap:4px; text-align:center; box-shadow:0 10px 25px rgba(0,0,0,0.5);\">\n      <span style=\"font-size:18px;\">\xF0\x9F\x91\x87 \xEB\xB0\x91\xEC\x9D\x98 \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80\xEB\xA5\xBC \xEA\xB8\xB8\xEA\xB2\x8C \xEA\xBE\xB9 \xEB\x88\x8C\xEB\x9F\xAC\xEC\xA3\xBC\xEC\x84\xB8\xEC\x9A\x94 \xF0\x9F\x91\x87</span>\n      <span style=\"color:#3b82f6; font-size:13px; margin-top:4px;\">'\xEC\x82\xAC\xEC\xA7\x84 \xEC\x95\xB1\xEC\x97\x90 \xEC\xA0\x80\xEC\x9E\xA5' (\xEB\x98\x90\xEB\x8A\x94 \xEC\x9D\xB4\xEB\xAF\xB8\xEC\xA7\x80 \xEC\xA0\x80\xEC\x9E\xA5) \xEC\x84\xA0\xED\x83\x9D</span>\n    </div>\n    <img id=\"downloadedImagePreview\" src=\"\" style=\"max-width:90%; max-height:60vh; border-radius:12px; box-shadow:0 10px 25px rgba(0,0,0,0.5); border:1px solid rgba(255,255,255,0.2);\">\n    <button onclick=\"document.getElementById('imageDownloadModal').style.display='none'\" style=\"margin-top:24px; background:#475569; color:white; border:1px solid #64748b; padding:12px 32px; border-radius:99px; font-weight:900; font-size:16px; cursor:pointer; box-shadow:0 4px 12px rgba(0,0,0,0.3);\">\xEB\x8B\xAB\xEA\xB8\xB0</button>\n  </div>\n</div>\n".freeze


















































































































































































































































































































































































































































; _erbout
